name: Test workflow
# Test workflow

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.md'
  merge_group:
    branches:
      - develop

jobs:
  init-github-context:
    runs-on: ubuntu-latest
    outputs:
      repo-branch: ${{ steps.extract-branch.outputs.repo-branch }}

    steps:
      - uses: actions/checkout@v3
      - id: extract-branch
        run: |
          GITHUB_EVENT_NAME=${{ github.event_name }}
          if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
            GITHUB_REF=${{ github.ref }}
          elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            GITHUB_REF=refs/heads/${{ github.head_ref }}
          elif [[ "$GITHUB_EVENT_NAME" == "merge_group" ]]; then
            GITHUB_REF=refs/heads/${{ github.head_ref }}
          else
            echo "Failed to extract branch information"
            exit 1
          fi
          echo "repo-branch=${GITHUB_REF/refs\/heads\//""}" >> $GITHUB_OUTPUT
          echo "event=${GITHUB_EVENT_NAME}" >> $GITHUB_OUTPUT
          
      - name: Echo event
        run: |
          echo "${{ steps.extract-branch.outputs.repo-branch }}"
          echo "${{ steps.extract-branch.outputs.event }}"
          
