name: Test workflow
# Test workflow

on:
  workflow_dispatch:
    inputs:
      repo-owner:
        description: 'The git repo owner'
        required: true
        type: string
      repo-name:
        description: 'The git repo name'
        required: true
        type: string
      repo-branch:
        description: 'The git branch name'
        required: true
        type: string

jobs:
  init-github-context:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        id: echo info
        run: |
          echo "${{ secrets.WF_TOKEN }}"
          echo "${{ inputs.repo-owner }}"
          echo "${{ inputs.repo-name }}"
          echo "${{ inputs.repo-branch }}"
          
